export { default as Navbar }      from './Navbar'
export { default as Hero }        from './Hero'
export { default as AppMockup }   from './AppMockup'
export { default as HowItWorks }  from './HowItWorks'
export { default as Features }    from './Features'
export { default as Download }    from './Download'
export { default as Footer }      from './Footer'
